language: minimal

services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t u-reverse-proxy . 
  - docker tag u-reverse-proxy harunrst/u-reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push harunrst/u-reverse-proxy